vich_uploader:
      db_driver: orm

      mappings: 
          images:
              uri_prefix: /uploads/images
              upload_destination: '%kernel.project_dir%/public/uploads/images'

easy_admin:
    entities:
        Owner:
            class: App\Entity\BusStation
            form:
                fields: [{ property: 'images', type: 'collection', type_options: { entry_type: 'App\Form\BusStationType' }}]
            list:
                fields: ['id','name']
              